### ISSUE TITLE
Is this tool working, at least kind of?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [denniskrupke/ros2unity#3]
Hello, thank you for sharing your great work here.
You mention this project is in progress, but I was wondering if it is still working partially?

**Comment by denniskrupke** [comment]
Hi there, sorry for the late response. Yes, it is working. In our institute we used it for different kinds of bi-directional communication between ROS and Unity. E.g. controlling a hand, streaming video, moving a mobile robot, spawning (in Unity) detected objects (with ROS), using moveit to plan a trajectory for pick-and-place with a robotic manipulator. 
But there is no tutorial. And the code is not clean, due to the lack of available man-power for coding. The most recent commented and probably easy-to-use example relies on the "phantom_pick" branch.
Please check this out, it has many bugs fixed:
https://github.com/denniskrupke/ros2unity/tree/phantom_pick

And there is a paper about the concept:
https://www.researchgate.net/publication/319397765_Prototyping_of_Immersive_HRI_Scenarios
Just ask, if you have further questions
